notifications:
  email: false
  slack: thunderducks:LC3z1hKqrNtlFLtF9AsXZjVF

language: node_js
node_js:
- stable

addons:
  ssh_known_hosts:
  - israndom.win:123

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm run build

after_success:
- "curl -H 'Content-Type: application/json' --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/kostecki/megapanel/trigger/62ace418-1bb4-405c-832a-b20e289fb35c/"
