language: node_js
node_js:
  - "stable"

addons:
  ssh_known_hosts:
    - israndom.win

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build

before_deploy:
- chmod 600 .travis/id_rsa.enc && mv .travis/id_rsa.enc ~/.ssh/id_rsa

deploy:
  provider: script
  script: scp -P 123 $TRAVIS_BUILD_DIR/build $SSH_USER@$SSH_HOST:$REMOTE_DIR
  on:
    branch: master