language: node_js
node_js:
- stable

addons:
  ssh_known_hosts:
  - israndom.win:123

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_bcaf09bc0ad7_key -iv $encrypted_bcaf09bc0ad7_iv -in id_rsa.enc -out .travis/id_rsa -d

install:
  - npm install

script:
  - npm run build

before_deploy:
  - chmod 600 .travis/id_rsa && mv .travis/id_rsa ~/.ssh/id_rsa

deploy:
  skip_cleanup: true
  provider: script
  script: scp -P 123 -r $TRAVIS_BUILD_DIR/build $SSH_USER@$SSH_HOST:$REMOTE_DIR
  on:
    branch: master
