notifications:
  email: false
  slack: thunderducks:LC3z1hKqrNtlFLtF9AsXZjVF
language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - israndom.win
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_d999d88b8e5c_key -iv $encrypted_d999d88b8e5c_iv -in .travis/id_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: scp -P 123 -r $TRAVIS_BUILD_DIR/build/* $SSH_USER@$SSH_HOST:$REMOTE_DIR
  on:
    branch: master
