notifications:
  email: false
  slack: thunderducks:LC3z1hKqrNtlFLtF9AsXZjVF

language: node_js
node_js:
- stable

addons:
  ssh_known_hosts:
  - israndom.win:123

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm run build

after_success:
- $DOCKER_HUB_TRIGGER
