notifications:
  email: false
  slack: thunderducks:$SLACK_TOKEN

stages:
  - "Build Project"
  - "Build Docker Image"

sudo: required

branches:
  only:
  - feature/docker_in_travis

services:
  - docker

language: node_js
node_js:
  - stable

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: "Build Project"
      install:
      - npm install
      
      script:
      - npm run build
    
    - stage: "Build Docker Image"
      script: docker build -t kostecki/megapanel .

before_deploy:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  docker push kostecki/megapanel