notifications:
  email: false
  slack:
    rooms:
      secure: 1vIwPwaJZqqiSo2vzM4f4mygf1WdkbZ9VPiwQNRJvNc2fEEZz+qYgUbPgvMXCFSZuRWDR2JefsUaqIQP/1YKtzV8sGeLwcIrYLwzJmi1I01v2laT1GIQQ7uFPdeOiRY+LKMtQI4iddaEbxfDno/NTv5Tzj1Jm719yjkoziYFos28FX+beIieCU97VtS7hN/yMes2VP2dNmXufHAAVileGSDEUys6sYVgaFpWEAyJm9l3PxsvoVn69ZJmrvLGBaR1bweYhU7uH7CYr6POaEVpJD8wVt6qhsaPpJFu3Lx9rOE8cQpTKSerkygqECu/Z/JV5ccKBMfRgXdzGF1wB7MED17rOxmY6rW8M9ewmNtwgtpaNpRUv0TPkr8gQGWvv82/tNGT5cT8iWtCaBACbvRbn1RjUT/c4ZzRXT3tmtrfda7GHHFMgDrXT5iKhBTuVA6sUbkB6cKuLpgqko2+ofa4kz0wQyNY+X+GMQ2NHsmMvqWle9Pdgiry8Oe8cvijM2MTggQvaYFcg5x2TRkR3yH++Q20WLi3K2AWbGOkh1Tc60kg09E/cI+D8QeJJ7UmnVt2GfAmNZyRfPEuvf0cRzKPcR0rkhMpsQMal7B/KLNJ9bP/jmtNmeXLLZUlzEkOmtxFPcQUR+2cfrZafwBEOeirPJmwCZ3i42Qv1VlKYLl30VY=
sudo: required
branches:
  only:
  - master
services:
- docker
script:
- docker build --build-arg api_user=$REACT_APP_API_USER --build-arg api_pass=$REACT_APP_API_PASS -t kostecki/megapanel .
deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push kostecki/megapanel
after_success:
  script:
    - python rancher_upgrade.py