version: '3.7'

services:
  dev:
    container_name: MEGAPanel-DEV
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - './megapanel:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_USER
      - REACT_APP_API_PASS
